# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
    branches: [ "**" ]
    paths:
    - .github/**
    - src/**
    - test/**
    tags: [ "v**" ]
  workflow_dispatch: {}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      node-version: 18.x  # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      release: ${{startsWith(github.ref, 'refs/tags/')}}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{env.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.node-version}}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - if: always()
      run: npm run test
    - run: npm run publish:extension
      env: { VSCE_PAT: "${{secrets.vscode_marketplace_token}}" }
      if: env.release == 'true'
    - run: npm run package:cli
      if: env.release == 'true'
    - name: Release
      if: env.release == 'true'
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: "ranger*"
